#!/bin/bash

IFNAME="$(ip link show | grep 'wg_' | cut -d ' ' -f 2 | sed 's/://' | sed 's/wg_//' | tr '[:lower:]' '[:upper:]' | sed 's/_D/ (dpi)/')"

if [ ! -z "${IFNAME}" ]; then
    echo "🛡️ ${IFNAME}"
fi
