require("config.plugins.lualine")
require("config.plugins.nvim-autopairs")
require("config.plugins.nvim-cmp")
require("config.plugins.nvim-tree")
require("config.plugins.telescope")
require("config.plugins.treesitter")
