return {
    'isobit/vim-caddyfile',
    'rcarriga/nvim-notify',
    'stefandtw/quickfix-reflector.vim',
    'tpope/vim-fugitive',
    'junegunn/vim-peekaboo',
    'tpope/vim-sleuth',
    'vim-scripts/iptables',
    { 'akinsho/bufferline.nvim', opts = {}, dependencies = { 'navarasu/onedark.nvim' } },
    { 'ethanholz/nvim-lastplace', opts = {} },
    { 'folke/todo-comments.nvim', opts = {} },
    { 'kylechui/nvim-surround', version = '*', event = 'VeryLazy', opts = {} },
    { 'lukas-reineke/indent-blankline.nvim', main = 'ibl', opts = {} },
    { 'norcalli/nvim-colorizer.lua', opts={ '*' }, dependencies = { 'navarasu/onedark.nvim' } },
    -- { 'wakatime/vim-wakatime', event = 'VeryLazy' },
    { 'williamboman/mason.nvim', opts = {} },
    'Winseven4lyf/vim-bbcode',
}
