return {
  'numToStr/Navigator.nvim',
  'tpope/vim-fugitive',
  'tpope/vim-rhubarb',
  'tpope/vim-sleuth',
  'tpope/vim-surround',
  'tmux-plugins/vim-tmux',
  'nvim-lualine/lualine.nvim',
  'nvim-tree/nvim-tree.lua',
  'nvim-tree/nvim-web-devicons',
  'Civitasv/cmake-tools.nvim',
  'rcarriga/nvim-notify',
  { 'numToStr/Comment.nvim', opts = {} },
  { 'akinsho/bufferline.nvim', config = {} },
  { 'ethanholz/nvim-lastplace', config = {} },
  { 'wakatime/vim-wakatime', event = 'VeryLazy' },
}
